// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDts617juQO5FTNth3lGdBh7sQqDvU450Y',
    appId: '1:610702554815:web:7ebfe25d0b6933a361780a',
    messagingSenderId: '610702554815',
    projectId: 'mad-act12-spring26',
    authDomain: 'mad-act12-spring26.firebaseapp.com',
    storageBucket: 'mad-act12-spring26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYKHR2zDqJsvSp2FwfSizd5kzQE05nz3A',
    appId: '1:610702554815:android:52850d3d28177a6261780a',
    messagingSenderId: '610702554815',
    projectId: 'mad-act12-spring26',
    storageBucket: 'mad-act12-spring26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsxoh4A8bOguJNRRtcmWudOlTM_yGzibY',
    appId: '1:610702554815:ios:d43c97bc55f186d161780a',
    messagingSenderId: '610702554815',
    projectId: 'mad-act12-spring26',
    storageBucket: 'mad-act12-spring26.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsxoh4A8bOguJNRRtcmWudOlTM_yGzibY',
    appId: '1:610702554815:ios:d43c97bc55f186d161780a',
    messagingSenderId: '610702554815',
    projectId: 'mad-act12-spring26',
    storageBucket: 'mad-act12-spring26.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDts617juQO5FTNth3lGdBh7sQqDvU450Y',
    appId: '1:610702554815:web:48825dd963d17fc861780a',
    messagingSenderId: '610702554815',
    projectId: 'mad-act12-spring26',
    authDomain: 'mad-act12-spring26.firebaseapp.com',
    storageBucket: 'mad-act12-spring26.firebasestorage.app',
  );

}